import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Navbar
    select_branch: "Select Branch",
    login: "Login",
    sign_up: "Sign Up",
    my_profile: "My Profile",
    my_orders: "My Orders",
    settings: "Settings",
    logout: "Logout",
    search_placeholder: "Ask Simba AI: 'I need breakfast items'...",
    
    // Home
    show_filters: "Show Filters",
    hide_filters: "Hide Filters",
    active_filters: "Active Filters:",
    clear_all: "Clear All",
    filters_title: "Filters",
    price_range: "Price Range (RWF)",
    categories: "Categories",
    show_more: "Show More",
    show_less: "Show Less",
    hero_badge: "Rwanda's No. 1 Supermarket",
    hero_title_1: "Freshness",
    hero_title_2: "Delivered",
    hero_description: "A testament to Rwanda's economic resurgence, meeting all your daily needs—from fresh food to furniture and beyond.",
    shop_now: "Shop Now",
    results_for: "Results for your selection",
    view_all: "View All",
    no_matches: "No matches found",
    no_matches_desc: "Try adjusting your filters or search terms to find what you're looking for.",
    select_branch_reminder: "Please select a branch to see real-time stock levels and place orders.",

    // Footer
    footer_desc: "Rwanda's leading online supermarket. Fresh products delivered to your doorstep.",
    shop: "Shop",
    support: "Support",
    stay_updated: "Stay Updated",
    newsletter_desc: "Subscribe to our newsletter for latest offers.",
    all_rights: "All rights reserved.",
    groceries: "Groceries",
    electronics: "Electronics",
    home_kitchen: "Home & Kitchen",
    personal_care: "Personal Care",
    contact_us: "Contact Us",
    faqs: "FAQs",
    shipping_policy: "Shipping Policy",
    returns: "Returns",

    // ProductCard
    out_of_stock: "Out of Stock",
    only_left: "Only {stock} Left",
    in_stock: "In Stock",
    add_to_cart: "Add to Cart",

    // Cart
    cart_title: "My Cart",
    your_cart: "Your Cart",
    empty_cart: "Your cart is empty",
    empty_cart_desc: "Looks like you haven't added anything to your cart yet. Explore our products and find something you love!",
    total: "Total",
    checkout: "Checkout",
    subtotal: "Subtotal",
    summary: "Order Summary",
    continue_shopping: "Continue Shopping",
    remove: "Remove",
    delivery_fee: "Delivery Fee",
    free: "FREE",
    proceed_to_checkout: "Proceed to Checkout",
    secure_checkout_badge: "Secure Checkout powered by Simba",
    start_shopping: "Start Shopping",
    clear_cart: "Clear Cart",
    go_to_shop: "Go to Shop",
    minimum_order_title: "Minimum order is {amount}",
    minimum_order_desc: "Add {remaining} more to checkout. This helps keep Simba deliveries logistically viable.",

    // Checkout
    secure_checkout: "Secure Checkout",
    fulfillment_method: "Delivery or Pickup",
    fulfillment_method_desc: "Choose how you want to receive your order",
    delivery_option: "Delivery",
    delivery_option_desc: "Simba brings the order to your address.",
    pickup_option: "Pickup",
    pickup_option_desc: "Collect your prepared order at your selected branch.",
    select_fulfillment_branch: "Fulfillment Branch",
    where_collect: "Fulfillment location for your order",
    choose_branch: "Choose a Simba branch",
    change_branch: "Change Branch",
    contact_number: "Contact Number",
    contact_number_desc: "We will use this number for order updates",
    delivery_address: "Delivery Address",
    delivery_address_placeholder: "e.g., Gisozi, Gasabo, Kigali",
    delivery_address_desc: "Enter your physical delivery address",
    momo_deposit: "MoMo Deposit",
    secure_order_deposit: "Secure your order with a small deposit",
    deposit_desc: "To confirm your order, a refundable deposit of {amount} RWF is required. This prevents no-shows and ensures your items are prepared.",
    remaining_balance_desc: "Remaining balance is paid upon delivery.",
    mtn_phone: "MTN Phone Number",
    grand_total: "Grand Total",
    pay_now: "Pay Now (Deposit)",
    pay_pickup_deposit: "Deposit",
    pickup_deposit_due_now: "Pickup Deposit Due Now",
    pickup_balance_due: "Balance Due at Pickup",
    pickup_deposit_note: "{deposit} is deducted from your order. You will pay {balance} when you pick it up.",
    place_order: "Place Order",
    pay_on_delivery: "Pay on Delivery",
    creating_order: "Creating your order...",
    connecting_momo: "Connecting to MoMo...",
    waiting_confirmation: "Waiting for confirmation...",
    confirm_prompt: "Please confirm the {amount} RWF prompt on your phone.",
    secure_delivery_badge: "Secure Delivery by Simba",
    fill_all_details: "Please fill in all delivery and payment details.",
    invalid_phone: "Enter a valid Rwandan number (e.g. +250781234567)",
    address_label: "Delivery Address",
    phone_label: "Phone Number",
    address_placeholder: "e.g., Gisozi, Gasabo, Kigali",
    address_required: "Delivery address is required",
    phone_required: "A valid phone number is required",
    delivery_instructions: "Delivery Instructions & Landmarks",
    delivery_instructions_placeholder: "e.g., Opposite Gisozi Sector Office or Near the pharmacy",
    delivery_instructions_desc: "Add landmarks to help our team locate you",
    pickup_instructions: "Pickup Notes",
    pickup_instructions_placeholder: "e.g., I will collect after 5 PM",
    pickup_instructions_desc: "Optional notes for the branch team",
    minimum_order_error: "Your cart needs to be at least {amount} before checkout.",
    payment_failed: "Payment failed or was cancelled.",
    payment_timeout: "Payment timeout. Please check your MoMo app.",
    
    // Product Detail
    description: "Description",
    similar_products: "Similar Products",
    add_to_cart_btn: "Add to Cart",
    added_to_cart: "Added to Cart",
    back_to_shop: "Back to Shop",
    product_not_found: "Product Not Found",
    product_not_found_desc: "We couldn't find the product you're looking for. It might have been removed or the link is incorrect.",
    home: "Home",
    save_percent: "SAVE 20%",
    fast_delivery: "Fast Delivery",
    quality: "Quality",
    you_may_also_like: "You May Also Like",
    no_stock: "No Stock",
    select_branch_btn: "Select branch",

    // Category Page
    collection: "Collection",
    items_count: "{count} Items",
    under_5k: "Under 5k",
    clear_active_filters: "Clear Active Filters",

    // Auth
    login_title: "Login to Simba",
    register_title: "Join Simba Supermarket",
    email_label: "Email",
    password_label: "Password",
    full_name_label: "Full Name",
    account_type_label: "Account Type",
    assigned_branch_label: "Assigned Branch",
    logging_in: "Logging in...",
    creating_account: "Creating account...",
    dont_have_account: "Don't have an account?",
    already_have_account: "Already have an account?",
    register_here: "Register here",
    login_here: "Login here",
    back_to_home: "Back to Home",
    client_role: "Client (Shopper)",
    manager_role: "Branch Manager",
    staff_role: "Branch Staff",
    select_branch_placeholder: "Select your branch",
    forgot_password: "Forgot Password?",
    connect_with_google: "Connect with Google",
    reset_password_title: "Reset Your Password",
    send_reset_link: "Send Reset Link",
    back_to_login: "Back to Login",
    new_password_label: "New Password",
    confirm_password_label: "Confirm New Password",
    update_password: "Update Password",
    reset_link_sent: "Reset link sent to your email.",
    password_updated: "Password updated successfully!",
    
    // AI Chat
    ai_welcome: "Hello! I'm Simba AI. How can I help you find something today?",
    ai_thinking: "AI Thinking",
    recommended_items: "Recommended Items",
    type_message: "Type your message...",
    chat_with_ai: "Chat with Simba AI",

    // Concierge (service & account assistant)
    concierge_welcome: "Muraho! I'm Simba Concierge. Ask me about our branches, your account, deliveries, payments, or anything about Simba Supermarket.",
    concierge_subtitle: "Help & Info",
    concierge_placeholder: "Ask about branches, account, delivery...",
    concierge_thinking: "Concierge Thinking",
    concierge_tooltip: "Ask Simba Concierge",
    concierge_open_login: "Go to Login",
    concierge_open_register: "Create Account",
    concierge_open_reset_password: "Reset Password",
    concierge_open_orders: "My Orders",
    concierge_open_contact: "Contact Us",
    concierge_open_branches: "Our Branches",
    concierge_open_cart: "View Cart",
    concierge_open_about: "About Us",
    concierge_open_faqs: "FAQs",
    concierge_open_shipping_policy: "Shipping Policy",
    concierge_open_returns: "Returns",
    concierge_open_home: "Go Home",

    // Bottom navigation
    nav_shop: "Shop",
    nav_branch: "Branch",
    nav_account: "Account",
    nav_menu: "Menu",
    nav_home: "Home",
    language: "Language",
    about: "About",

    // Profile completion prompt
    complete_profile_title: "Complete your profile",
    complete_profile_desc: "Add your delivery address and phone number so we can deliver your orders.",
    save: "Save",
    later: "Later"
  },
  fr: {
    // Navbar
    select_branch: "Choisir une succursale",
    login: "Connexion",
    sign_up: "S'inscrire",
    my_profile: "Mon Profil",
    my_orders: "Mes Commandes",
    settings: "Paramètres",
    logout: "Déconnexion",
    search_placeholder: "Demandez à Simba AI: 'J'ai besoin d'articles de petit-déjeuner'...",

    // Home
    show_filters: "Afficher les filtres",
    hide_filters: "Masquer les filtres",
    active_filters: "Filtres actifs:",
    clear_all: "Tout effacer",
    filters_title: "Filtres",
    price_range: "Fourchette de prix (RWF)",
    categories: "Catégories",
    show_more: "Afficher plus",
    show_less: "Afficher moins",
    hero_badge: "Supermarché n°1 au Rwanda",
    hero_title_1: "Fraîcheur",
    hero_title_2: "Livrée",
    hero_description: "Un témoignage de la renaissance économique du Rwanda, répondant à tous vos besoins quotidiens—de la nourriture fraîche aux meubles et au-delà.",
    shop_now: "Acheter maintenant",
    results_for: "Résultats pour votre sélection",
    view_all: "Voir tout",
    no_matches: "Aucun résultat trouvé",
    no_matches_desc: "Essayez d'ajuster vos filtres ou vos termes de recherche pour trouver ce que vous cherchez.",
    select_branch_reminder: "Veuillez sélectionner une succursale pour voir les niveaux de stock en temps réel et passer des commandes.",

    // Footer
    footer_desc: "Le premier supermarché en ligne du Rwanda. Produits frais livrés à votre porte.",
    shop: "Boutique",
    support: "Support",
    stay_updated: "Restez à jour",
    newsletter_desc: "Inscrivez-vous à notre newsletter pour les dernières offres.",
    all_rights: "Tous droits réservés.",
    groceries: "Épicerie",
    electronics: "Électronique",
    home_kitchen: "Maison & Cuisine",
    personal_care: "Soins personnels",
    contact_us: "Contactez-nous",
    faqs: "FAQs",
    shipping_policy: "Politique d'expédition",
    returns: "Retours",

    // ProductCard
    out_of_stock: "En rupture de stock",
    only_left: "Plus que {stock} restants",
    in_stock: "En stock",
    add_to_cart: "Ajouter au panier",

    // Cart
    cart_title: "Mon Panier",
    your_cart: "Votre Panier",
    empty_cart: "Votre panier est vide",
    empty_cart_desc: "Il semble que vous n'ayez encore rien ajouté à votre panier. Explorez nos produits et trouvez quelque chose que vous aimez !",
    total: "Total",
    checkout: "Payer",
    subtotal: "Sous-total",
    summary: "Résumé de la commande",
    continue_shopping: "Continuer vos achats",
    remove: "Supprimer",
    delivery_fee: "Frais de livraison",
    free: "GRATUIT",
    proceed_to_checkout: "Passer à la caisse",
    secure_checkout_badge: "Paiement sécurisé par Simba",
    start_shopping: "Commencer vos achats",
    clear_cart: "Vider le panier",
    go_to_shop: "Aller à la boutique",
    minimum_order_title: "Commande minimum de {amount}",
    minimum_order_desc: "Ajoutez encore {remaining} pour passer à la caisse. Cela aide Simba à organiser les livraisons.",

    // Checkout
    secure_checkout: "Paiement Sécurisé",
    fulfillment_method: "Livraison ou retrait",
    fulfillment_method_desc: "Choisissez comment recevoir votre commande",
    delivery_option: "Livraison",
    delivery_option_desc: "Simba apporte la commande à votre adresse.",
    pickup_option: "Retrait",
    pickup_option_desc: "Récupérez votre commande préparée dans la succursale choisie.",
    select_fulfillment_branch: "Succursale de préparation",
    where_collect: "Lieu de préparation de votre commande",
    choose_branch: "Choisissez une succursale Simba",
    change_branch: "Changer de succursale",
    contact_number: "Numéro de contact",
    contact_number_desc: "Nous utiliserons ce numéro pour les mises à jour de commande",
    delivery_address: "Adresse de livraison",
    delivery_address_placeholder: "ex : Gisozi, Gasabo, Kigali",
    delivery_address_desc: "Entrez votre adresse physique de livraison",
    momo_deposit: "Dépôt MoMo",
    secure_order_deposit: "Sécurisez votre commande avec un petit dépôt",
    deposit_desc: "Pour confirmer votre commande, un dépôt remboursable de {amount} RWF est requis. Cela évite les absences et garantit que vos articles sont préparés.",
    remaining_balance_desc: "Le solde restant est payé à la livraison.",
    mtn_phone: "Numéro de téléphone MTN",
    grand_total: "Total général",
    pay_now: "Payer maintenant (Dépôt)",
    pay_pickup_deposit: "Dépôt",
    pickup_deposit_due_now: "Dépôt de retrait à payer maintenant",
    pickup_balance_due: "Solde à payer au retrait",
    pickup_deposit_note: "{deposit} est déduit de votre commande. Vous paierez {balance} lors du retrait.",
    place_order: "Passer la commande",
    pay_on_delivery: "Payer à la livraison",
    creating_order: "Création de votre commande...",
    connecting_momo: "Connexion à MoMo...",
    waiting_confirmation: "En attente de confirmation...",
    confirm_prompt: "Veuillez confirmer l'invite de {amount} RWF sur votre téléphone.",
    secure_delivery_badge: "Livraison sécurisée par Simba",
    fill_all_details: "Veuillez remplir tous les détails de livraison et de paiement.",
    invalid_phone: "Entrez un numéro rwandais valide (ex. +250781234567)",
    address_label: "Adresse de livraison",
    phone_label: "Numéro de téléphone",
    address_placeholder: "ex : Gisozi, Gasabo, Kigali",
    address_required: "L'adresse de livraison est requise",
    phone_required: "Un numéro de téléphone valide est requis",
    delivery_instructions: "Instructions de livraison et points de repère",
    delivery_instructions_placeholder: "ex : En face du bureau de secteur de Gisozi ou près de la pharmacie",
    delivery_instructions_desc: "Ajoutez des points de repère pour aider notre équipe à vous localiser",
    pickup_instructions: "Notes de retrait",
    pickup_instructions_placeholder: "ex : Je passerai après 17 h",
    pickup_instructions_desc: "Notes facultatives pour l'équipe de la succursale",
    minimum_order_error: "Votre panier doit atteindre au moins {amount} avant le paiement.",
    payment_failed: "Le paiement a échoué ou a été annulé.",
    payment_timeout: "Délai de paiement dépassé. Veuillez vérifier votre application MoMo.",

    // Product Detail
    description: "Description",
    similar_products: "Produits similaires",
    add_to_cart_btn: "Ajouter au panier",
    added_to_cart: "Ajouté au panier",
    back_to_shop: "Retour à la boutique",
    product_not_found: "Produit non trouvé",
    product_not_found_desc: "Nous n'avons pas pu trouver le produit que vous recherchez. Il a peut-être été supprimé ou le lien est incorrect.",
    home: "Accueil",
    save_percent: "ÉCONOMISEZ 20%",
    fast_delivery: "Livraison rapide",
    quality: "Qualité",
    you_may_also_like: "Vous aimerez peut-être aussi",
    no_stock: "Pas de stock",
    select_branch_btn: "Choisir une branche",

    // Category Page
    collection: "Collection",
    items_count: "{count} Articles",
    under_5k: "Moins de 5k",
    clear_active_filters: "Effacer les filtres actifs",

    // Auth
    login_title: "Connexion à Simba",
    register_title: "Rejoindre Simba Supermarket",
    email_label: "Email",
    password_label: "Mot de passe",
    full_name_label: "Nom complet",
    account_type_label: "Type de compte",
    assigned_branch_label: "Succursale assignée",
    logging_in: "Connexion en cours...",
    creating_account: "Création du compte...",
    dont_have_account: "Vous n'avez pas de compte ?",
    already_have_account: "Vous avez déjà un compte ?",
    register_here: "Inscrivez-vous ici",
    login_here: "Connectez-vous ici",
    back_to_home: "Retour à l'accueil",
    client_role: "Client (Acheteur)",
    manager_role: "Gérant de succursale",
    staff_role: "Personnel de succursale",
    select_branch_placeholder: "Sélectionnez votre succursale",
    forgot_password: "Mot de passe oublié ?",
    connect_with_google: "Se connecter avec Google",
    reset_password_title: "Réinitialiser votre mot de passe",
    send_reset_link: "Envoyer le lien",
    back_to_login: "Retour à la connexion",
    new_password_label: "Nouveau mot de passe",
    confirm_password_label: "Confirmer le mot de passe",
    update_password: "Mettre à jour",
    reset_link_sent: "Lien envoyé à votre adresse email.",
    password_updated: "Mot de passe mis à jour avec succès !",

    // AI Chat
    ai_welcome: "Bonjour ! Je suis Simba AI. Comment puis-je vous aider à trouver quelque chose aujourd'hui ?",
    ai_thinking: "Réflexion de l'IA",
    recommended_items: "Articles recommandés",
    type_message: "Tapez votre message...",
    chat_with_ai: "Discuter avec Simba AI",

    // Concierge (service & account assistant)
    concierge_welcome: "Bonjour ! Je suis Simba Concierge. Posez-moi des questions sur nos succursales, votre compte, les livraisons, les paiements ou tout sur Simba Supermarket.",
    concierge_subtitle: "Aide & Infos",
    concierge_placeholder: "Succursales, compte, livraison...",
    concierge_thinking: "Concierge réfléchit",
    concierge_tooltip: "Demander au Concierge",
    concierge_open_login: "Aller à la connexion",
    concierge_open_register: "Créer un compte",
    concierge_open_reset_password: "Réinitialiser",
    concierge_open_orders: "Mes commandes",
    concierge_open_contact: "Nous contacter",
    concierge_open_branches: "Nos succursales",
    concierge_open_cart: "Voir le panier",
    concierge_open_about: "À propos",
    concierge_open_faqs: "FAQ",
    concierge_open_shipping_policy: "Livraison",
    concierge_open_returns: "Retours",
    concierge_open_home: "Accueil",

    // Bottom navigation
    nav_shop: "Boutique",
    nav_branch: "Filiale",
    nav_account: "Compte",
    nav_menu: "Menu",
    nav_home: "Accueil",
    language: "Langue",
    about: "À propos",

    // Profile completion prompt
    complete_profile_title: "Complétez votre profil",
    complete_profile_desc: "Ajoutez votre adresse de livraison et votre numéro pour recevoir vos commandes.",
    save: "Enregistrer",
    later: "Plus tard"
  },
  kin: {
    // Navbar
    select_branch: "Hitamo Ishami",
    login: "Injira",
    sign_up: "Iyandikishe",
    my_profile: "Umwirondoro wanjye",
    my_orders: "Ibyo nategetse",
    settings: "Igenamiterere",
    logout: "Sohoka",
    search_placeholder: "Baza Simba AI: 'Nkeneye ibyo kurya by'igitondo'...",

    // Home
    show_filters: "Yerekana Utuyunguruzo",
    hide_filters: "Hisha Utuyunguruzo",
    active_filters: "Utuyunguruzo dukoreshwa:",
    clear_all: "Siba byose",
    filters_title: "Utuyunguruzo",
    price_range: "Ikiguzi (RWF)",
    categories: "Ibyiciro",
    show_more: "Yerekana ibindi",
    show_less: "Yerekana bike",
    hero_badge: "Supermarket ya mbere mu Rwanda",
    hero_title_1: "Ibiryo Bishya",
    hero_title_2: "Bikugezeho",
    hero_description: "Ikimenyetso cy'izahuka ry'ubukungu bw'u Rwanda, duhaza ibyo ukeneye byose buri munsi—kuva ku biryo bishya kugeza ku bikoresho byo munzu n'ibindi.",
    shop_now: "Gura ubu",
    results_for: "Ibisubizo by'ibyo wahisemo",
    view_all: "Reba byose",
    no_matches: "Nta bisubizo bibonetse",
    no_matches_desc: "Gerageza guhindura utuyunguruzo cyangwa ibyo ushakisha kugira ngo ubone icyo ukeneye.",
    select_branch_reminder: "Hitamo ishami kugira ngo urebe ibihari ubashe no kugura.",

    // Footer
    footer_desc: "Supermarket ya mbere ikorera kuri interineti mu Rwanda. Ibiryo bishya bikugezeho ku muryango.",
    shop: "Iduka",
    support: "Ubufasha",
    stay_updated: "Menya amakuru mashya",
    newsletter_desc: "Iyandikishe kugira ngo ubone amakuru y'inyungu nshya.",
    all_rights: "Uburenganzira bwose ni ubwacu.",
    groceries: "Ibiribwa",
    electronics: "Ibikoresho by'ikoranabuhanga",
    home_kitchen: "Ibikoresho byo mu rugo",
    personal_care: "Iby'isuku",
    contact_us: "Twandikire",
    faqs: "Ibibazo bikunze kubazwa",
    shipping_policy: "Amategeko yo kohereza",
    returns: "Ibisubizwa",

    // ProductCard
    out_of_stock: "Ntabihari",
    only_left: "Hasigaye {stock} gusa",
    in_stock: "Bihari",
    add_to_cart: "Shyira mu gitebo",

    // Cart
    cart_title: "Ibiri mu gitebo",
    your_cart: "Igitebo cyawe",
    empty_cart: "Igitebo cyawe ntakirimo",
    empty_cart_desc: "Urabona nta kintu na kimwe urashyira mu gitebo cyawe. Reba ibyo dufite uhitemo ibyo ukunda!",
    total: "Byose hamwe",
    checkout: "Ishyura",
    subtotal: "Igiciro mbumbe",
    summary: "Inshamake y'ibyo uze kugura",
    continue_shopping: "Komeza guhaha",
    remove: "Siba",
    delivery_fee: "Ikiguzi cyo kugezwaho ibintu",
    free: "BY'UBUNTU",
    proceed_to_checkout: "Jya kwishyura",
    secure_checkout_badge: "Kwishyura bifite umutekano na Simba",
    start_shopping: "Tangira guhaha",
    clear_cart: "Siba ibiri mu gasanduku",
    go_to_shop: "Jya ku isoko",
    minimum_order_title: "Igiciro fatizo ni {amount}",
    minimum_order_desc: "Ongeramo ibifite agaciro ka {remaining} kugira ngo ukomeze kwishyura. Ibi bifasha Simba gutegura uko ibintu bigezwa ku bakiriya.",

    // Checkout
    secure_checkout: "Kwishyura Umutekano",
    fulfillment_method: "Kugezwaho cyangwa gufata",
    fulfillment_method_desc: "Hitamo uko ushaka kwakira ibyo watumije",
    delivery_option: "Kugezwaho",
    delivery_option_desc: "Simba izakuzanira ibyo watumije aho uherereye.",
    pickup_option: "Kubyifatira",
    pickup_option_desc: "Uzafata ibyo watumije ku ishami wahisemo.",
    select_fulfillment_branch: "Ishami ry'iyuzuzwa",
    where_collect: "Aho ibyo waguze bizaturuka",
    choose_branch: "Hitamo ishami rya Simba",
    change_branch: "Hindura ishami",
    contact_number: "Nimero yo kuguhamagara",
    contact_number_desc: "Tuzayikoresha tukumenyesha uko itumizwa ryawe rimeze",
    delivery_address: "Aho uherereye (Aho bigezwa)",
    delivery_address_placeholder: "Urugero: Gisozi, Gasabo, Kigali",
    delivery_address_desc: "Andika aho uherereye neza",
    momo_deposit: "Ingwate ya MoMo",
    secure_order_deposit: "Rinda ibyo wategetse utanga ingwate nshya",
    deposit_desc: "Kugira ngo wemeze ibyo wategetse, urasabwa gutanga ingwate y'amafaranga {amount} RWF asubizwa. Ibi bituma ibyo waguze bitegurwa.",
    remaining_balance_desc: "Ayasigaye yishyurirwa ugejejweho ibintu.",
    mtn_phone: "Nimero ya MTN",
    grand_total: "Igiciro cyose hamwe",
    pay_now: "Ishyura ubu (Ingwate)",
    pay_pickup_deposit: "Ingwate",
    pickup_deposit_due_now: "Ingwate yo gufata yishyurwa ubu",
    pickup_balance_due: "Asigaye yishyurwa ufata ibyo watumije",
    pickup_deposit_note: "{deposit} ikurwa ku giciro cyose. Uzishyura {balance} igihe uzabifatirira.",
    place_order: "Tuma Itumwa",
    pay_on_delivery: "Ishyura ugejejweho ibintu",
    creating_order: "Turimo gutegura ibyo watumije...",
    connecting_momo: "Turimo guhura na MoMo...",
    waiting_confirmation: "Tegereze kwemeza...",
    confirm_prompt: "Emeza kwishyura {amount} RWF kuri terefone yawe.",
    secure_delivery_badge: "Kugezwaho ibintu bifite umutekano na Simba",
    fill_all_details: "Andika neza aho uzafatira n'uburyo bwo kwishyura.",
    invalid_phone: "Injiza nimero y'u Rwanda igenga (urugero: +250781234567)",
    address_label: "Aderesi y'iperereza",
    phone_label: "Nimero ya telefoni",
    address_placeholder: "Urugero: Gisozi, Gasabo, Kigali",
    address_required: "Aderesi y'iperereza irakenewe",
    phone_required: "Nimero ya telefoni y'agenga irakenewe",
    delivery_instructions: "Ibyerekeye aho uherereye n'aho bageza ibintu",
    delivery_instructions_placeholder: "Urugero: Imbere y'ibiro by'Umurenge wa Gisozi cyangwa Hafi ya farumasi",
    delivery_instructions_desc: "Andika ibimenyetso bifasha kugeza ibintu aho uri",
    pickup_instructions: "Icyitonderwa cyo kubifata",
    pickup_instructions_placeholder: "Urugero: Nzabifata nyuma ya saa kumi n'imwe",
    pickup_instructions_desc: "Icyitonderwa kidateganyijwe ku bakozi b'ishami",
    minimum_order_error: "Igitebo cyawe kigomba nibura kugira agaciro ka {amount} mbere yo kwishyura.",
    payment_failed: "Kwishyura ntibyagenze neza cyangwa byahagaritswe.",
    payment_timeout: "Igihe cyo kwishyura cyarenze. Reba muri porogaramu ya MoMo.",

    // Product Detail
    description: "Ibisobanuro",
    similar_products: "Ibindi bisa n'ibi",
    add_to_cart_btn: "Shyira mu gitebo",
    added_to_cart: "Byashyizwe mu gitebo",
    back_to_shop: "Subira mu duka",
    product_not_found: "Igicuruzwa nticyabonetse",
    product_not_found_desc: "Ntitwashoboye kubona igicuruzwa ushaka. Gishobora kuba cyakuweho cyangwa imenyekanisha ririho ririmo amakosa.",
    home: "Ahabanza",
    save_percent: "GABANYIRIZWA 20%",
    fast_delivery: "Kugezwaho vuba",
    quality: "Ubwiza",
    you_may_also_like: "Ibindi washima",
    no_stock: "Ntabihari",
    select_branch_btn: "Hitamo ishami",

    // Category Page
    collection: "Ibyatoranyijwe",
    items_count: "Ibintu {count}",
    under_5k: "Munsi ya 5k",
    clear_active_filters: "Siba utuyunguruzo twose",

    // Auth
    login_title: "Injira muri Simba",
    register_title: "Iyandikishe muri Simba Supermarket",
    email_label: "Email",
    password_label: "Ijambo ry'ibanga",
    full_name_label: "Amazina yose",
    account_type_label: "Ubwoko bwa konti",
    assigned_branch_label: "Ishami ukoreramo",
    logging_in: "Turimo kwinjira...",
    creating_account: "Turimo gukora konti...",
    dont_have_account: "Nta konti ufite?",
    already_have_account: "Ufite konti umaze kuyikora?",
    register_here: "Iyandikishe hano",
    login_here: "Injira hano",
    back_to_home: "Subira ahabanza",
    client_role: "Umukiriya (Uguha)",
    manager_role: "Umuyobozi w'ishami",
    staff_role: "Umukozi w'ishami",
    select_branch_placeholder: "Hitamo ishami ryawe",
    forgot_password: "Waba wibagiwe ijambo ry'ibanga?",
    connect_with_google: "Koresha Google kwinjira",
    reset_password_title: "Hindura ijambo ry'ibanga",
    send_reset_link: "Ohereza aho guhindurira",
    back_to_login: "Subira ahabanza kwinjira",
    new_password_label: "Ijambo ry'ibanga rishya",
    confirm_password_label: "Emeza ijambo ry'ibanga",
    update_password: "Hindura ubu",
    reset_link_sent: "Ubutumwa bwo guhindura bwoherejwe kuri email yawe.",
    password_updated: "Ijambo ry'ibanga ryahindutse neza!",

    // AI Chat
    ai_welcome: "Muraho! Ndi Simba AI. Nagufasha ute kubona icyo ukeneye uyu munsi?",
    ai_thinking: "AI iri gutekereza",
    recommended_items: "Ibyo twaguhitiramo",
    type_message: "Andika ubutumwa...",
    chat_with_ai: "Ganira na Simba AI",

    // Concierge (service & account assistant)
    concierge_welcome: "Muraho! Ndi Simba Concierge. Mbibaze kuri filiali zacu, konti yawe, ibicuruzwa, kwishyura, cyangwa ikindi kiri kuri Simba Supermarket.",
    concierge_subtitle: "Ubufasha & Amakuru",
    concierge_placeholder: "Filiali, konti, ibicuruzwa...",
    concierge_thinking: "Concierge iri gutekereza",
    concierge_tooltip: "Baza Simba Concierge",
    concierge_open_login: "Jya k'winjira",
    concierge_open_register: "Kora konti",
    concierge_open_reset_password: "Sanya ijambo ry'ibanga",
    concierge_open_orders: "Amatora yanjye",
    concierge_open_contact: "Twandikire",
    concierge_open_branches: "Amashami yacu",
    concierge_open_cart: "Reba igitebo",
    concierge_open_about: "Abyerekeye",
    concierge_open_faqs: "Ibibazo bisanzwe",
    concierge_open_shipping_policy: "Politiki y'iperereza",
    concierge_open_returns: "Isubizo",
    concierge_open_home: "Subira ahabanza",

    // Bottom navigation
    nav_shop: "Iduka",
    nav_branch: "Filiali",
    nav_account: "Konti",
    nav_menu: "Ivyo wemerera",
    nav_home: "Ahabanza",
    language: "Ururimi",
    about: "Amakuru",

    // Profile completion prompt
    complete_profile_title: "Uzuza amakuru yawe",
    complete_profile_desc: "Ongeramo aderesi yawe y'iperereza n'umurongo wa telefoni kugirango dushobore kuguha itumizwa ryawe.",
    save: "Bika",
    later: "Nyuma"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('simba_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('simba_lang', language);
  }, [language]);

  const t = (key) => {
    if (!translations[language]) {
      return translations['en'][key] || key;
    }
    return translations[language][key] || key;
  };

  const value = {
    language,
    setLanguage,
    t
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
